### ISSUE TITLE
Request: License

### ISSUE THREAD

**Issue by at3560k** [daniellawrence/ansible-puppetmaster#7]
I would appreciate being able to fork this for professional purposes.

https://github.com/blog/1530-choosing-an-open-source-license
https://help.github.com/articles/open-source-licensing/

**Comment by daniellawrence** [comment]
Thanks for the heads up.

Resolved with https://github.com/daniellawrence/ansible-puppetmaster/commit/7068562072eaa0890085cddc70b247e7954ac6bc
