### ISSUE TITLE
Fail on running 

### ISSUE THREAD

**Issue by JoshuaEdwards1991** [daniellawrence/ansible-puppetmaster#9]
My install appears to be failing on the yum section, any ideas why this would happen?

TASK [Install all the required packaes for a puppetmaster [yum]] ***************

NO MORE HOSTS LEFT *************************************************************
 [WARNING]: Could not create retry file 'install.retry'.         [Errno 13] Permission denied:
'install.retry'

**Comment by daniellawrence** [comment]
This is setup for debian/ubuntu, thats why the yum commands are failing.

**Comment by JoshuaEdwards1991** [comment]
ok so the puppet master will need to be debian / ubuntu?

**Comment by daniellawrence** [comment]
@JoshuaEdwards1991 Either only using debian/ubuntu or you could have a go at updating the playbook to support both.
